#!/bin/bash

set -o nounset
set -o errexit

if [ $(which kdialog 2> /dev/null) ]; then
	DIALOG=kdialog
else
	DIALOG="xterm -e dialog"
fi

svn commit -m "Committed via ROX, $(date)" "$@" > /tmp/kdialog 2>&1

$DIALOG --textbox /tmp/kdialog 640 400 \
	--title "Committing $@ to Subversion repository"

rm -f /tmp/kdialog
