#!/bin/bash

set -o nounset
set -o errexit

if [ $(which kdialog 2> /dev/null) ]; then
	DIALOG=kdialog
else
	DIALOG="xterm -e dialog"
fi

svn status "$@" 2>&1 | sort > /tmp/kdialog

$DIALOG --textbox /tmp/kdialog 640 400 --title "svn status" 

rm -f /tmp/kdialog
