(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "misc" :family "fixed"))))
 '(calendar-today ((((class color) (type tty) (background dark)) (:foreground "white" :background "red" :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "white" :background "red" :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "white" :background "red" :bold nil :underline nil))))
 '(dired-face-directory ((((class color) (type tty) (background dark)) (:foreground "blue" :background nil :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "darkorchid" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "cyan" :background nil :bold t :underline nil))))
 '(dired-face-executable ((((class color) (type tty) (background dark)) (:foreground "green" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "forestgreen" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "green" :background nil :bold t :underline nil))))
 '(font-lock-comment-face ((((class color) (type tty) (background dark)) (:foreground "red" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "red" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "red" :background nil :bold t :underline nil))))
 '(font-lock-doc-string-face ((((class color) (type tty) (background dark)) (:foreground "green" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "forestgreen" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "green" :background nil :bold t :underline nil))))
 '(font-lock-function-name-face ((((class color) (type tty) (background dark)) (:foreground "blue" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "mediumblue" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "yellow" :background nil :bold t :underline nil))))
 '(font-lock-keyword-face ((((class color) (type tty) (background dark)) (:foreground "white" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "black" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "white" :background nil :bold t :underline nil))))
 '(font-lock-preprocessor-face ((((class color) (type tty) (background dark)) (:foreground "blue" :background nil :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "navy" :background nil :bold t :underline nil)) (((class color) (type x) (background dark)) (:foreground "blue" :background nil :bold t :underline nil))))
 '(font-lock-reference-face ((((class color) (type tty) (background dark)) (:foreground "red" :background nil :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "orangered" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "pink" :background nil :bold t :underline nil))))
 '(font-lock-string-face ((((class color) (type tty) (background dark)) (:foreground "green" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "forestgreen" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "green" :background nil :bold t :underline nil))))
 '(font-lock-type-face ((((class color) (type tty) (background dark)) (:foreground "cyan" :background nil :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "darkorchid" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "cyan" :background nil :bold nil :underline nil))))
 '(font-lock-variable-name-face ((((class color) (type tty) (background dark)) (:foreground "yellow" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "blueviolet" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "gold" :background nil :bold t :underline nil))))
 '(holiday ((((class color) (type tty) (background dark)) (:foreground "white" :background "blue" :bold nil :underline nil)) (((class color) (type x) (background light)) (:foreground "white" :background "blue" :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "white" :background "blue" :bold nil :underline nil))))
 '(info-node ((((class color) (type tty) (background dark)) (:foreground "yellow" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "red" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "yellow" :background nil :bold t :underline nil))))
 '(info-xref ((((class color) (type tty) (background dark)) (:foreground "green" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "blue" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "green" :background nil :bold t :underline nil))))
 '(isearch ((((class color) (type tty) (background dark)) (:foreground "white" :background "green" :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "black" :background "aquamarine" :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "black" :background "green" :bold nil :underline nil))))
 '(man-bold ((((class color) (type tty) (background dark)) (:foreground "red" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "red" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "red" :background nil :bold nil :underline nil))))
 '(man-heading ((((class color) (type tty) (background dark)) (:foreground "blue" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "blue" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "blue" :background nil :bold nil :underline nil))))
 '(man-italic ((((class color) (type tty) (background dark)) (:foreground "blue" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "forestgreen" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "blue" :background nil :bold nil :underline nil))))
 '(man-xref ((((class color) (type tty) (background dark)) (:foreground "yellow" :background nil :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "magenta" :background nil :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "yellow" :background nil :bold nil :underline nil))))
 '(mode-line ((((class color) (type tty) (background dark)) (:foreground "black" :background "white" :bold t :underline nil)) (((class color) (type x) (background light)) (:foreground "lightgray" :background "black" :bold nil :underline nil)) (((class color) (type x) (background dark)) (:foreground "black" :background "white" :bold nil :underline nil)))))
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-save-interval 30)
 '(column-number-mode t)
 '(delete-auto-save-files nil)
 '(display-time-mode t)
 '(inhibit-startup-screen t)
 '(tab-width 4))
