#!/bin/bash

xrandr -q | grep "DP3 connected" && \
    xrandr --output DP3 --mode 2560x1440 --rate 59.95 --output eDP1 --auto --left-of DP3
xrandr -q | grep "DP-1-3 connected" && \
    xrandr --output DP-1-3 --mode 2560x1440 --rate 59.95 --output eDP1 --auto --left-of DP3

OPENBOX_DIR=$HOME/workspace/configs/openbox

setxkbmap -layout us

if [ -x $OPENBOX_DIR/setlayout ]; then
    echo found $OPENBOX_DIR/setlayout
    $OPENBOX_DIR/setlayout 0 3 3 0
else
    if [ - f $OPENBOX_DIR/setlayout.c ]; then
	echo found $OPENBOX_DIR/setlayout.c
	gcc $OPENBOX_DIR/setlayout.c -o $OPENBOX_DIR/setlayout
	$OPENBOX_DIR/setlayout 0 3 3 0
    fi
fi
    
xscreensaver &
gkrellm &
xfce4-panel &
nitrogen --restore &
audacious &
which workrave && workrave &

pidgin &

sleep 5 && kdeinit4 &

test -x /opt/toggldesktop/TogglDesktop.sh && /opt/toggldesktop/TogglDesktop.sh &
#which btsync && sleep 60 && btsync --storage ~/.btsync
#which slack && sleep 120 && slack &
