#!/bin/bash

MAIN_DISPLAY=$(xrandr -q | grep 'connected 1920x1080' | cut -d ' ' -f 1)
EXT_DISPLAY=$(xrandr -q | grep 'connected 2560x1440' | cut -d ' ' -f 1)
if [ -n "$MAIN_DISPLAY" -a -n "$EXT_DISPLAY" ]; then
    xrandr --output $EXT_DISPLAY --mode 2560x1440 --rate 59.95 --output $MAIN_DISPLAY --auto --left-of $EXT_DISPLAY
fi


OPENBOX_DIR=$HOME/workspace/configs/openbox

setxkbmap -layout us

if [ -x $OPENBOX_DIR/setlayout ]; then
    echo found $OPENBOX_DIR/setlayout
    $OPENBOX_DIR/setlayout 0 3 3 0
else
    if [ - f $OPENBOX_DIR/setlayout.c ]; then
	echo found $OPENBOX_DIR/setlayout.c
	gcc $OPENBOX_DIR/setlayout.c -o $OPENBOX_DIR/setlayout
	$OPENBOX_DIR/setlayout 0 3 3 0
    fi
fi
    
xscreensaver &
gkrellm &
xfce4-panel &
nitrogen --restore &
audacious &
which workrave && workrave &

pidgin &

sleep 5 && kdeinit5 &
sleep 20 && /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd & 
test -x /opt/toggldesktop/TogglDesktop.sh && /opt/toggldesktop/TogglDesktop.sh &
#which btsync && sleep 60 && btsync --storage ~/.btsync
#which slack && sleep 120 && slack &
